#ifndef G_CONSTANTS_H_
#define G_CONSTANTS_H_

// ENTITIES
#define MAX_ENTITIES 			32
#define ENTITY_DESTRUCT_TIME 	10000
#define ENTITY_SPAWN_TIME		10000
#define AI_IDLE_MIN_RENEW_TIME 	800
#define AI_IDLE_MAX_RENEW_TIME 	1500
#define AI_CHASE_MIN_RENEW_TIME 400
#define AI_CHASE_MAX_RENEW_TIME 800
#define SPOT_DISTANCE			300
#define MAX_CONFIGS				64

// PHYSICS
#define GRAVITY					180.0
#define JUMP_FORCE				-100.0
#define PLAYER_SPEED			20.0
#define SKELETON_SPEED			15.0
#define KNOCKBACK_STRENGTH		20.0

// COMBAT
#define SKELETON_STRENGTH		1
#define SKELETON_HP				4
#define	SKELETON_ATK_DIST		24
#define SKELETON_DMG_SPR		3
#define PLAYER_STRENGTH			2
#define PLAYER_HP				6
#define PLAYER_ATK_DIST			32
#define PLAYER_DMG_SPR			2

// RENDERER
#define SCR_LOGICAL_WIDTH 		320
#define SCR_LOGICAL_HEIGHT 		240
#define TORCH_FRMS_COUNT 		5
#define PLAYER_WLK_FRMS_COUNT	8
#define SKELETON_WLK_FRMS_COUNT 8
#define SKELETON_SPN_FRMS_COUNT 10
#define SKELETON_DTH_FRMS_COUNT	7
#define SKELETON_ANG_FRMS_COUNT	11
#define SKELETON_ATK_FRMS_COUNT	9
#define ANIM_TIME 				200
#define TILE_SPR_SIZE 			16
#define ENT_SPR_SIZE 			32
#define FONT_SPR_SIZE			8
#define FONT_SPR_PER_ROW		16
#define MAX_SPRITES				16

// LOCATION
#define MAX_OBJS 				32
#define MAX_MAP_COLUMNS 		64
#define MAX_MAP_ROWS 			12
#define MAX_MAPS 				1

// I/O
#define STICK_DEADZONE			8000

// DEBUG
#define DEBUG_TEXT_LENGTH 64

enum ENTITY_DIR
{
	DIR_LEFT,
	DIR_RIGHT
};

enum ENTITY_STATE
{
	STATE_NONE,
    STATE_SPAWNING,
    STATE_REMOVING,
	STATE_ANGER,
	STATE_ATTACK,
	STATE_HURT
};

enum ENTITY_AI
{
	AI_NONE,
	AI_IDLE,
	AI_CHASING
};

enum ENTITY_ID
{
	PLAYER,
	SKELETON
};

enum OBJ_ID
{
	TORCH,
	DECORATION,
	CHEST
};

enum MAP_ID
{
	TOMB
};

enum UI_ID
{
	FONT,
	HEALTH_BAR
};

#endif /* G_CONSTANTS_H_ */
