#ifndef G_CONSTANTS_H_
#define G_CONSTANTS_H_

// ENTITIES
#define MAX_ENTITIES 			32
#define ENTITY_DESTRUCT_TIME 	10000
#define ENTITY_SPAWN_TIME		10000
#define AI_IDLE_MIN_RENEW_TIME 	800
#define AI_IDLE_MAX_RENEW_TIME 	1500
#define AI_CHASE_MIN_RENEW_TIME 400
#define AI_CHASE_MAX_RENEW_TIME 800
#define SPOT_DISTANCE			800

// COMBAT
#define SKELETON_STRENGTH		1
#define SKELETON_HP				2
#define PLAYER_STRENGTH			2
#define PLAYER_HP				6

// RENDERER
#define LOGICAL_WIDTH 			1920
#define LOGICAL_HEIGHT 			1080
#define WALK_FRAMES_COUNT 		8
#define OBJ_FRAMES_COUNT 		5
#define SPAWN_FRAMES_COUNT		10
#define DEATH_FRAMES_COUNT		7
#define ANGER_FRAMES_COUNT		11
#define ATTACK_FRAMES_COUNT		9
#define ANIM_TIME 				200
#define TILE_SPRITE_SIZE 		16
#define TILE_SPRITE_SCALE 		6
#define ENTITY_SPRITE_SIZE 		32
#define ENTITY_SPRITE_SCALE	 	5
#define MAX_SPRITES				16

// LOCATION
#define MAX_OBJECTS 			32
#define MAX_MAP_COLUMNS 		64
#define MAX_MAP_ROWS 			12
#define MAX_LOCATIONS 			1

// I/O
#define STICK_DEADZONE			8000

enum KEY_STATE
{
    KEY_STATE_UP,
    KEY_STATE_DOWN,
	KEY_STATE_AXIS
};

enum ENTITY_DIR
{
	LEFT,
	RIGHT
};

enum ENTITY_ID
{
	PLAYER,
	SKELETON
};

enum ENTITY_STATE
{
	STATE_NONE,
    STATE_SPAWNING,
    STATE_REMOVING,
	STATE_ANGER,
	STATE_ATTACK
};

enum ENTITY_AI
{
	AI_NONE,
	AI_IDLE,
	AI_CHASING
};

enum OBJ_ID
{
	TORCH,
	DECORATION,
	CHEST
};

#endif /* G_CONSTANTS_H_ */
